"""user added with chat as it's child with a one to many relatationsship

Revision ID: 0a0ff321242e
Revises: 7fcb558a6ab7
Create Date: 2025-12-05 01:53:22.913095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0ff321242e'
down_revision: Union[str, Sequence[str], None] = '7fcb558a6ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_chats_phone_number'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('last_time_verfication_code_sent')
        batch_op.drop_column('phone_number_validated')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_validated', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('last_time_verfication_code_sent', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.drop_column('last_time_verfication_code_sent')
        batch_op.drop_column('phone_number_validated')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone_number_validated', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))
        batch_op.add_column(sa.Column('last_time_verfication_code_sent', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_chats_phone_number'), ['phone_number'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
