"""deleted units because it is uncecassary for the direction we're going

Revision ID: 236bed100966
Revises: 7905ae9ca131
Create Date: 2025-12-08 19:07:34.346161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236bed100966'
down_revision: Union[str, Sequence[str], None] = '7905ae9ca131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
