"""changed teh name of otp_token

Revision ID: 4d6fb82b34ea
Revises: 2504aeb5c127
Create Date: 2026-02-28 05:13:32.262522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6fb82b34ea'
down_revision: Union[str, Sequence[str], None] = '2504aeb5c127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=False),
    sa.Column('phone_number_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=True),
    sa.Column('national_id_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sheba_number', sa.String(length=26), nullable=True),
    sa.Column('sheba_number_validated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('full_nane', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('sheba_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_users')
    # ### end Alembic commands ###
