"""empty message

Revision ID: 53ee973556e3
Revises: 821ae28fa91a
Create Date: 2025-12-28 06:13:59.613088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ee973556e3'
down_revision: Union[str, Sequence[str], None] = '821ae28fa91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               server_default='1',
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               server_default=None,
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_nullable=False)

    # ### end Alembic commands ###
