"""add phone_number with unique constraint

Revision ID: 79100bba5271
Revises: bd07f8a9c977
Create Date: 2025-11-16 01:36:38.302337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79100bba5271'
down_revision: Union[str, Sequence[str], None] = 'bd07f8a9c977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_chats_phone_number', ['phone_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chats_phone_number', type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
