"""updated the chat output data model

Revision ID: 7c3237e7aa81
Revises: f8fe0060c8ce
Create Date: 2026-02-07 21:38:36.658157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c3237e7aa81"
down_revision: Union[str, Sequence[str], None] = "f8fe0060c8ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("buttons", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_button_name", ["name"])

    with op.batch_alter_table("chat_outputs", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_chat_output_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_outputs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_chat_output_name", type_="unique")

    with op.batch_alter_table("buttons", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint("uq_button_name", type_="unique")

    # ### end Alembic commands ###
