"""making the name of the placeholders uniqe was a mistake

Revision ID: 7db989ab2e1d
Revises: 8fa3b80db84c
Create Date: 2026-02-16 05:07:27.419013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db989ab2e1d'
down_revision: Union[str, Sequence[str], None] = '8fa3b80db84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeholders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_placeholder_name'), type_='unique')
        batch_op.create_unique_constraint('uq_placeholder_per_output', ['chat_output_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeholders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_placeholder_per_output', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_placeholder_name'), ['name'])

    # ### end Alembic commands ###
