"""update

Revision ID: 821ae28fa91a
Revises: a3ee9aafa07e
Create Date: 2025-12-18 18:22:05.617909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821ae28fa91a'
down_revision: Union[str, Sequence[str], None] = 'a3ee9aafa07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('emoji_symbol')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_symbol', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
