"""making the placeholder name uniqe wasn't a mistake

Revision ID: 8fa3b80db84c
Revises: e0aa963ac80a
Create Date: 2026-02-15 05:51:45.118099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fa3b80db84c"
down_revision: Union[str, Sequence[str], None] = "e0aa963ac80a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placeholders", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_placeholder_per_output"), type_="unique"
        )
        batch_op.create_unique_constraint("uq_placeholder_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placeholders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint("uq_placeholder_name", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_placeholder_per_output"), ["chat_output_id", "name"]
        )

    # ### end Alembic commands ###
