"""I added an emoji symbol for product for better dynamic adding and display of pruducts

Revision ID: a3ee9aafa07e
Revises: b66cd2a3b421
Create Date: 2025-12-14 03:58:50.936515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ee9aafa07e'
down_revision: Union[str, Sequence[str], None] = 'b66cd2a3b421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji_symbol', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('emoji_symbol')

    # ### end Alembic commands ###
