"""deleted units because it is uncecassary for the direction we're going

Revision ID: b66cd2a3b421
Revises: 236bed100966
Create Date: 2025-12-08 19:10:40.927909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66cd2a3b421'
down_revision: Union[str, Sequence[str], None] = '236bed100966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
