"""added last_time_verification_code_sent field as a timestamp to avoid spam

Revision ID: bc1efb956181
Revises: 9b23b9f545a9
Create Date: 2025-11-16 17:36:33.252256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1efb956181'
down_revision: Union[str, Sequence[str], None] = '9b23b9f545a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_time_verfication_code_sent', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('last_time_verfication_code_sent')

    # ### end Alembic commands ###
