"""place holder name needs to be uniqe

Revision ID: c1eee598e4b4
Revises: 7c3237e7aa81
Create Date: 2026-02-15 03:18:12.323646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1eee598e4b4"
down_revision: Union[str, Sequence[str], None] = "7c3237e7aa81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placeholders", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_placeholder_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("placeholders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint("uq_placeholder_name", type_="unique")

    # ### end Alembic commands ###
