"""making the placeholder name uniqe globally was a mistake

Revision ID: e0aa963ac80a
Revises: c1eee598e4b4
Create Date: 2026-02-15 03:46:48.233894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0aa963ac80a'
down_revision: Union[str, Sequence[str], None] = 'c1eee598e4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeholders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_placeholder_name'), type_='unique')
        batch_op.create_unique_constraint('uq_placeholder_per_output', ['chat_output_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeholders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_placeholder_per_output', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_placeholder_name'), ['name'])

    # ### end Alembic commands ###
