"""updated the relationship beteween the button and the button index

Revision ID: f8fe0060c8ce
Revises: 76055a8995eb
Create Date: 2026-02-04 00:54:27.258878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fe0060c8ce'
down_revision: Union[str, Sequence[str], None] = '76055a8995eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=600), nullable=False),
    sa.Column('callback_data', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_chat_output_name')
    )
    op.create_table('button_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_output_id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.ForeignKeyConstraint(['chat_output_id'], ['chat_outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_output_id', 'number', name='uq_button_index_order')
    )
    op.create_table('placeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_output_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('INLINE', 'OUTLINE', name='placeholdertypes'), nullable=False),
    sa.ForeignKeyConstraint(['chat_output_id'], ['chat_outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placeholders')
    op.drop_table('button_indexes')
    op.drop_table('chat_outputs')
    op.drop_table('buttons')
    # ### end Alembic commands ###
